.github/workflows/build-deb-v4.yml, stage/release-2_1/debian/bullseye/amd64/setup.sh, stage/release-2_1/debian/bullseye/package-model.json, stage/release-2_1/package-model.json, stage/release-2_1/ubuntu/jammy/package-model.json
Related to https://github.com/orgs/regolith-linux/discussions/792
This change copies the `release` stage from the 2.1 release into a `release-2_1` stage.  I've never tried rebuilding an older version so there maybe some unknown reason why this doesn't work.
I'd planned to copy the deb repo dirs from the server before running the 2.2 release but forgot so they were overwritten.  Had I done that this wouldn't be necessary.  In any case, a good way to test the robustness of the build system!
=> Add experimental stage to rebuild r2.1

stage/experimental/ubuntu/focal/package-model.json
See https://github.com/regolith-linux/voulage/actions/runs/3783013435/jobs/6431219813 for build failure.
=> Disable regolith-aviso on focal due to older dependency requirements

.github/scripts/ext-debian.sh, .github/workflows/build-deb-v4.yml
Testing support for publishing ubuntu source packages from unstable stage to launchpad.net.
This change will be tested after merging.
=> publish to launchpad

.github/scripts/ext-debian.sh
Change is an attempt (untested) to resolve issues like:
```
Rejected:
File regolith-look-default_0.7.5.orig.tar.gz already exists in unstable, but uploaded version has different contents. See more information about this error in https://help.launchpad.net/Packaging/UploadErrors.
File regolith-look-default_0.7.5-1regolith.debian.tar.xz already exists in unstable, but uploaded version has different contents. See more information about this error in https://help.launchpad.net/Packaging/UploadErrors.
Files specified in DSC are broken or missing, skipping package unpack verification.
```
=> Update changelog entry generation to be unique per codename

.github/scripts/ext-debian.sh
Launchpad.net (maybe upstream constraint, unsure) requires that for a given PPA, that a source package is globally unique.  However for regolith packages this is the exception: most packages work without changes across releases.  This change includes an external change in launchpad that creates a PPA per release.  This (hopefully) will sidestep the source publishing constraint at the cost of a more complex PPA setup.  (from one per stage to n per stage where n is the total number of supported Ubuntu releases)
=> seperate packages per codename for launchpad

stage/experimental/debian/bullseye/amd64/setup.sh, stage/release-2_1/debian/bullseye/amd64/setup.sh, stage/release-2_2/debian/bullseye/amd64/setup.sh, stage/release-3_0/debian/bullseye/amd64/setup.sh, stage/testing/debian/bullseye/amd64/setup.sh, stage/testing/debian/bullseye/package-model.json, stage/unstable/debian/bullseye/amd64/setup.sh, stage/unstable/debian/bullseye/package-model.json
Before we were using github managed servers for bullseye builds.  Something changed in them causing previously working builds to fail.  Decided to move to Regolith-managed hosts for more control.
=> Various fixes for bullseye

.github/workflows/build-deb-v4.yml, .github/workflows/test-desktop-installable2.yml
Some cosmetics cleanup of Github Actions files for better readability. Mostly:
- add empty lines between jobs
- correct indentation of one block
Also renamed one of the actions. This is just a personal preferences and can be removed if you feel like it.
```diff
- name: regolith-desktop is installable 2
+ name: Test regolith-desktop is installable
```
=> chore: cosmetic cleanup of actions files

.github/workflows/test-desktop-installable2.yml
The purpose of this PR is to move all the `test-$distro-$codename-action` repos into one single repository `test-desktopp-installable-action`. Note that I created [khos2ow/test-desktop-installable-action](https://github.com/khos2ow/test-desktop-installable-action) and consolidated all the codes from those repos. But this repo has to move into [regolith-linux](https://github.com/regolith-linux/) org before merging this PR.
=> feat: consolideate all the installable actions into one repo

stage/unstable/ubuntu/jammy/package-model.json
address https://github.com/regolith-linux/regolith-desktop/issues/920
=> fix: enable xdg-desktop-portal-regolith to build on jammy

.github/scripts/tag-stage.sh, stage/unstable/package-model.json
As per https://github.com/regolith-linux/regolith-rofi-config/pull/5 we are going to use master branch from now on.
Corresponding section in tag-stage.sh has been updated to reflect this change as well.
=> feat: use master branch for regolith-rofi-config

stage/testing/debian/bookworm/package-model.json, stage/testing/ubuntu/jammy/package-model.json, stage/unstable/debian/bookworm/package-model.json, stage/unstable/ubuntu/jammy/package-model.json
A dependency in regolith-session-flashback has been removed from the [Debian repos](https://packages.debian.org/bookworm/policykit-1-gnome).  This causes [failure at install time](https://github.com/regolith-linux/voulage/actions/runs/12979166882/job/36194602436) as `apt` cannot find the dependency.  Ubuntu [doesn't seem to have removed this package](https://launchpad.net/ubuntu/+source/policykit-1-gnome), so it doesn't seem like it matters either way there.  In this PR I set older distros to use the older package version that expresses the dependency.  Because the new behavior is on the `main` branch, newer distro/codenames will take the new package by default.
=> fix: build regolith-session on different branches due to package removal in debian testing

stage/unstable/package-model.json
It looks to be safe to build `regolith-avizo` for all the distros off top of `master`.
=> chore: build regolith-avizo from master

stage/testing/debian/testing/package-model.json, stage/testing/package-model.json, stage/testing/ubuntu/jammy/package-model.json, stage/testing/ubuntu/noble/package-model.json, stage/testing/ubuntu/oracular/package-model.json, stage/unstable/debian/testing/package-model.json, stage/unstable/package-model.json, stage/unstable/ubuntu/jammy/package-model.json, stage/unstable/ubuntu/noble/package-model.json, stage/unstable/ubuntu/oracular/package-model.json
Use the following primary ref for the provided packages:
- `i3status-rs`: use `ubuntu/v0.32.1` as primary ref and adjust the necessary distro overrides
- `regolith-control-center`: use `regolith/46` as primary ref and adjust the necessary distro overrides
This PR also adjusts the corresponding released tags of the above packages in the corresponding `stage/testing/` model files.
=> chore: modify primary ref for couple of packages

stage/testing/ubuntu/jammy/package-model.json, stage/unstable/package-model.json
- make sure package source name is consistent everywhere:
- `regolith-linux/WhiteSur-gtk-theme` must be camel case to be case sensitive
- `regolith-linux/python3-i3ipc` must end with `.git`
- enable `xdg-desktop-portal-regolith` for `jammy` on `testing`
=> chore: some fix and cleanup on package models

stage/testing/debian/testing/package-model.json, stage/unstable/debian/testing/package-model.json
libwlroot-dev was removed from Debian Trixie repos altogether and as such sway-regolith cannot be built. We will start using v1.10 for it. In the meantime disabling this to get the CI green.
=> chore: temporary disable sway-reglith on debian testing

stage/testing/ubuntu/noble/package-model.json, stage/testing/ubuntu/oracular/package-model.json, stage/unstable/ubuntu/noble/package-model.json, stage/unstable/ubuntu/oracular/package-model.json
Enable `ubiquity-slideshow-regolith` package for all the ~distros~ Ubuntu releases.
**Update:** Ubiquity only will be used in the ISOs where base distro is Ubuntu.
/ref: https://github.com/regolith-linux/ubiquity-slideshow-regolith/pull/3
=> feat: enable ubiquity-slideshow for all Ubuntu releases

stage/testing/debian/bookworm/package-model.json, stage/testing/debian/testing/package-model.json, stage/unstable/debian/bookworm/package-model.json, stage/unstable/debian/testing/package-model.json
Enabling `plymouth-theme-regolith` for all distros, specifically for debian.
=> chore: enable plymouth-theme for all distro

stage/unstable/ubuntu/plucky/package-model.json
Introducing Plucky in `unstable` stage for further testing and implementations. When the time comes it will be further promoted to `testing` stage, and the current plan is to be included in the upcoming `v3.3`  release.
=> feat: introduce plucky to unstable stage

stage/testing/ubuntu/jammy/package-model.json
Note: the version is set to `TBA` which will be generated and replaced properly after running update changelog version action.
=> chore: add xdg-desktop-portal-regolith to jammy testing

stage/unstable/ubuntu/plucky/package-model.json
* tested basics
* tested can update wallpaper
* didn't see any errors on console when launching
=> feat: add regolith-control-center ported from gnome 48

stage/testing/ubuntu/plucky/package-model.json
ref is set to `TBA` which will be updated by the corresponding downstream action.
=> feat: promote regolith-control-center to plucky testing

.github/workflows/build-deb-v5.yml
Historically we used to run test matrix right after packages were built and published. But most of the time the tests would fail (because we might have built only one package), or there are some skipped distros in the test matrix which would show up as failed.
=> fix: don't run tests after build

.github/workflows/test-desktop-installable2.yml
Unsure this is needed but wasn't seeing that Trixie is getting tested in the builder.  I also note that in testing Debian Trixie does not see any packages in the `testing` stage.
=> Add configuration to test debian trixie
